version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    container_name: flask_frontend
    ports:
      - "5050:5050"
    volumes:
      - ./frontend:/app
    restart: unless-stopped
    depends_on:
      - backend

  backend:
    build:
      context: .
    container_name: node_backend
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
    restart: unless-stopped
    command: sh -c "pip install mlflow scikit-learn pandas flask && npm install && node server.js"
