apiVersion: v1
kind: ConfigMap
metadata:
  name: airflow-config
data:
  AIRFLOW__CORE__EXECUTOR: CeleryExecutor
  AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres-service:5432/airflow
  AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://airflow:airflow@postgres-service:5432/airflow
  AIRFLOW__CELERY__BROKER_URL: redis://redis-service:6379/0
  AIRFLOW__CORE__LOAD_EXAMPLES: "true"
  AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "true"
